const arrayProductos = [
    {
        id:1,
        nombre: "Nike Dunk Brasil",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "dunk",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 200,
        cantColores: "2",
    },
    {
        id:2,
        nombre: "Nike Air Dunk Jumbo",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "dunk",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 400,
        cantColores: "3",
    },
    {
        id:3,
        nombre: "Nike Dunk Low Retro",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "dunk",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 600,
        cantColores: "4",
    },
    {
        id:4,
        nombre: "Air Jordan 4 Retro",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "jordan",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 359,
        cantColores: "2",
    },
    {
        id:5,
        nombre: "Air Jordan 3 Retro",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "jordan",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 359,
        cantColores: "1",
    },
    {
        id:6,
        nombre: "Air Jordan 5 Navy",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "jordan",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 379,
        cantColores: "1",
    },
    {
        id:7,
        nombre: "Air Jordan 1 Low",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "jordan",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 450,
        cantColores: "",
    },
    {
        id:8,
        nombre: "Air Jordan Low SE",
        descrip: "Zapatillas - Hombre",
        categoria: "zapatillas",
        modelo: "jordan",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 400,
        cantColores: "",
    },
    {
        id:9,
        nombre: "Nike Dri-FIT Stride",
        descrip: "Shorts - Hombre",
        categoria: "indumentaria",
        modelo: "dri-fit",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 50,
        cantColores: "",
    },
    {
        id:10,
        nombre: "Nike Dri-FIT Park 3",
        descrip: "Shorts - Hombre",
        categoria: "indumentaria",
        modelo: "dri-fit",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 80,
        cantColores: "",
    },
    {
        id:11,
        nombre: "Nike Dri-FIT Academy",
        descrip: "Shorts - Hombre",
        categoria: "indumentaria",
        modelo: "dri-fit",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 90,
        cantColores: "",
    },
    {
        id:12,
        nombre: "Jordan Jumpman",
        descrip: "Remeras - Hombre",
        categoria: "indumentaria",
        modelo: "jordan",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 60,
        cantColores: "",
    },
    {
        id:13,
        nombre: "Nike SB",
        descrip: "Remeras - Hombre",
        categoria: "indumentaria",
        modelo: "sb",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 63,
        cantColores: "",
    },
    {
        id:14,
        nombre: "Nike Sportswear",
        descrip: "Remeras - Hombre",
        categoria: "indumentaria",
        modelo: "Sportswear",
        img1: "1",
        img2: "2",
        img3: "3",
        precio: 44,
        cantColores: "",
    }
]